/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 132
#define YY_END_OF_BUFFER 133
static yyconst short int yy_accept[330] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  133,  132,
       87,   72,   88,  119,   45,   64,   89,   75,   76,   43,
       41,   83,   42,   82,   44,  123,  123,   84,   86,   50,
       57,   49,   81,  132,   90,   79,   80,   66,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   77,   65,   78,   67,
       98,  117,   99,  132,   99,   97,  118,  132,  122,  122,
       48,  119,   62,   70,   46,   60,   58,   59,   73,  130,
       61,  126,  123,    0,    0,    0,    2,   85,   68,   52,
       47,    0,   51,   69,    0,   93,   90,    0,    1,   90,

        1,   90,   90,   90,   90,   90,   90,   90,   13,   90,
       90,   90,   90,   90,   14,   21,   90,   90,   90,   90,
       26,   90,   90,   90,   90,   90,   90,   90,   90,   71,
       98,   96,  111,  112,  100,  115,  110,  102,  103,  108,
      106,  101,  107,  109,  104,  105,    0,   97,  113,  114,
        0,   63,   74,    0,    0,    0,    0,  126,    2,  125,
        0,  128,  124,    0,  123,    2,   53,   54,    0,   94,
       93,    0,    2,    1,    1,    1,    1,   90,    6,   90,
       90,   90,   90,   11,   90,   17,   90,   90,   90,   90,
       20,   90,   90,   24,   25,   90,   90,   90,   90,   90,

       90,   90,   90,   90,   90,   90,   90,   90,  115,  116,
        0,  130,    0,  130,  130,  131,    0,    2,    4,    2,
        0,  128,    0,    0,    3,    2,  129,    0,   94,    1,
        1,    1,    1,   90,   90,   90,    9,   90,   90,   15,
       90,   90,   55,   90,   90,   90,   23,   27,   90,   90,
       90,   31,   90,   33,   34,   90,   90,   90,   38,   90,
       90,  115,  116,  121,    0,  130,    0,    0,    0,    0,
      127,  126,    2,  125,  128,  124,    2,    0,    0,    0,
        1,    5,    7,    8,   10,   90,   16,   90,   90,   19,
       90,   90,   29,   90,   32,   35,   90,   37,   39,   40,

      130,  130,    0,  131,  131,  127,    0,  129,  129,    0,
      129,  120,   90,   18,   56,   22,   28,   30,   36,  131,
        0,  127,  129,    0,   90,  131,  129,   12,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   28,   28,   30,   28,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   32,   31,   31,
       33,   34,   35,   36,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   47,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[67] =
    {   0,
        1,    2,    1,    3,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    1,    6,    6,    6,    6,
        1,    1,    1,    1,    1,    1,    7,    6,    6,    6,
        8,    8,    1,    9,    1,    1,   10,   11,   11,   11,
       11,   11,   11,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,    3,    1,    3,    1
    } ;

static yyconst short int yy_base[346] =
    {   0,
        0,    0,   63,   66,   61,   64,   72,   75,  893,  939,
      939,  863,  939,    0,  857,  869,  939,  939,  939,   62,
      850,  939,  845,   61,  843,  117,   72,  842,  939,   59,
       64,   60,  939,  835,    0,  939,  939,  939,   93,   89,
       78,  101,  100,  104,  110,  836,  126,   91,  129,   90,
       79,  109,  142,  112,  145,  146,  939,  751,  939,  939,
        0,  939,  751,  194,  939,    0,  939,  160,  939,  771,
      939,    0,  939,  939,  788,  939,  939,  939,  795,  188,
      939,  202,  239,  100,  228,    0,  245,  939,  939,  784,
      784,  765,  939,  939,    0,    0,    0,  253,  260,  791,

      268,  150,   60,  151,  158,  159,  155,  161,  790,  167,
      168,  186,  165,  171,  789,  788,  169,  170,  212,  237,
      787,  251,  219,  176,  174,  226,  252,  274,  276,  939,
        0,  939,  939,  939,  939,  281,  939,  939,  939,  939,
      939,  939,  939,  939,  939,  939,    0,    0,  939,  939,
      749,  939,  939,  293,  303,  307,  313,  319,  323,  327,
      284,  333,  748,  348,  354,  360,  939,  939,  735,    0,
        0,  369,  375,  381,  390,  396,  402,  281,  742,  228,
      291,  320,  299,  344,  388,  741,  366,  331,  387,  348,
      739,  368,  402,  738,  736,  408,  413,  414,  333,  416,

      417,  420,  421,  422,  425,  423,  426,  427,  426,    0,
      708,  460,  428,  464,  474,  488,  437,  495,  502,  509,
      105,  516,  468,    0,  523,  530,  539,  698,    0,  545,
      553,  560,  566,  439,  458,  450,  712,  481,  523,  711,
      339,  455,  939,  451,  502,  540,  708,  707,  508,  437,
      536,  706,  537,  704,  703,  553,  546,  560,  682,  572,
      578,  939,  939,  939,  581,  587,  593,  603,  608,  611,
      615,  621,  625,  629,  636,  659,  650,  657,  666,  644,
      671,  664,  635,  633,  603,  622,  601,  650,  332,  580,
      656,  657,  573,  642,  530,  516,  593,  509,  452,  280,

      683,  687,  641,  692,  713,  697,  718,  722,  728,  663,
      743,  939,  579,  223,  939,  173,  164,  157,   92,  749,
      754,  758,  764,  770,  435,  774,  779,  939,  939,  816,
      827,  838,  849,  854,  860,  867,  878,  889,  895,  897,
      903,  909,  915,  921,  927
    } ;

static yyconst short int yy_def[346] =
    {   0,
      329,    1,  330,  330,  331,  331,  332,  332,  329,  329,
      329,  329,  329,  333,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  334,  335,  329,  329,  329,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  329,  329,  329,  329,
      337,  329,  329,  329,  329,  338,  329,  329,  329,  329,
      329,  333,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  339,  329,  329,  329,  329,
      329,  329,  329,  329,  340,  341,  335,  329,  336,  336,

      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  329,
      337,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  342,  338,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  339,  329,  329,  329,  329,  329,  329,  343,
      341,  329,  329,  329,  336,  336,  329,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,

      336,  336,  336,  336,  336,  336,  336,  336,  329,  344,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  345,  329,  329,  329,  329,  343,  329,
      329,  329,  329,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  329,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  345,  329,  329,  329,  329,
      329,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  336,  336,  329,  336,  336,  336,  336,  329,
      329,  329,  329,  329,  336,  329,  329,  329,    0,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329
    } ;

static yyconst short int yy_nxt[1006] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   27,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   35,   35,
       35,   35,   36,   10,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   46,   47,   46,   46,   46,   48,
       49,   50,   46,   46,   51,   52,   53,   54,   46,   55,
       46,   56,   57,   58,   59,   60,   62,   63,   67,   62,
       63,   67,   75,   10,  329,   79,   10,   80,   80,   80,
       80,   89,   90,   93,   94,   76,   82,   91,   83,   83,
       83,   83,  329,  329,   68,   70,   64,   68,   70,   64,

      179,   85,   92,  329,  329,  329,  329,   98,   87,   99,
       99,   99,   99,   85,  329,  329,  160,  160,  329,  104,
      122,  274,  274,  329,  329,   65,  329,   65,   65,  101,
       65,   82,  105,   83,   83,   83,   83,  102,  106,  103,
      329,  108,  117,  329,  121,   84,   85,  113,   86,  107,
      123,  109,  110,   87,  111,   84,  329,  112,   85,  329,
      329,  114,  127,  149,  329,  329,  124,  150,  115,  329,
      118,  329,  329,  329,  119,  329,  116,   86,  329,  329,
      120,  329,  329,  329,  329,  329,  125,  329,  329,  128,
      329,  129,  183,  137,  180,  178,  126,  133,  134,  181,

      329,  135,  154,  184,   80,   80,   80,   80,  186,  192,
      136,  136,  136,  190,  182,  201,  157,  155,  158,  158,
      158,  158,  185,  187,  156,  191,  329,  137,  200,  155,
      193,  138,  139,  329,  188,  140,  141,  329,  159,  161,
      329,  161,  329,  189,  142,  162,  162,  162,  143,  144,
      145,  329,  146,   82,  147,   83,   83,   83,   83,  164,
      194,  165,  165,  165,  165,  329,  329,  199,   85,  172,
      172,  172,  172,  235,  174,   87,  175,  175,  175,  175,
       85,  166,  177,  202,  175,  175,  175,  175,  329,  173,
      329,  196,  203,  195,  329,  329,  176,  209,  209,  209,

      204,  162,  162,  162,  176,  329,  197,  198,  205,  212,
      212,  212,  212,  329,  213,  206,  213,  208,  234,  207,
      214,  214,  214,  215,  215,  215,  215,  157,  236,  216,
      216,  216,  216,  157,  329,  158,  158,  158,  158,  219,
      219,  219,  219,  160,  160,  329,  329,  329,  217,  222,
      222,  222,  222,  329,  238,  218,  243,  315,  329,  220,
      217,  237,  329,  221,  225,  225,  225,  225,   82,  223,
      165,  165,  165,  165,  164,  252,  227,  227,  227,  227,
      329,  287,  329,   85,  226,  172,  172,  172,  172,  239,
       87,  172,  172,  172,  172,   85,  166,  230,  230,  230,

      230,  329,  329,  245,  174,  173,  175,  175,  175,  175,
      177,  173,  175,  175,  175,  175,  329,  231,  232,  232,
      232,  232,  329,  242,  244,  246,  176,  329,  329,  240,
      329,  329,  176,  241,  329,  329,  329,  329,  233,  329,
      329,  329,  262,  262,  262,  214,  214,  214,  270,  329,
      270,  329,  249,  329,  271,  271,  271,  253,  247,  248,
      328,  255,  256,  257,  329,  329,  329,  254,  250,  329,
      258,  251,  329,  259,  260,  261,  212,  212,  212,  212,
      266,  266,  266,  266,  275,  275,  275,  275,  154,  155,
      215,  215,  215,  215,  282,  329,  265,  284,  293,  289,

      267,  155,  157,  155,  216,  216,  216,  216,  283,  288,
      156,  272,  272,  272,  272,  155,  329,  268,  219,  219,
      219,  219,  329,  329,  269,  219,  219,  219,  219,  268,
      329,  273,  222,  222,  222,  222,  285,  329,  220,  225,
      225,  225,  225,  290,  329,  220,  225,  225,  225,  225,
      329,  329,  223,  278,  329,  227,  227,  227,  227,  277,
      329,  230,  230,  230,  230,  292,  277,  329,  279,  230,
      230,  230,  230,  286,  329,  166,  232,  232,  232,  232,
      279,  231,  232,  232,  232,  232,  329,  329,  291,  231,
      294,  295,  329,  329,  329,  296,  281,  301,  301,  301,

      301,  297,  281,  266,  266,  266,  266,  329,  298,  302,
      302,  302,  302,  299,  303,  329,  303,  329,  300,  325,
      304,  304,  304,  267,  305,  305,  305,  305,  271,  271,
      271,  306,  306,  306,  306,  157,  329,  272,  272,  272,
      272,  308,  308,  308,  308,  274,  274,  329,  319,  329,
      217,  307,  275,  275,  275,  275,  329,  218,  304,  304,
      304,  273,  217,  313,  329,  221,  225,  225,  225,  225,
      329,  329,  223,  309,  309,  309,  309,  310,  329,  310,
      311,  311,  311,  311,  311,  311,  277,  232,  232,  232,
      232,  314,  318,  173,  312,  224,  329,  316,  317,  301,

      301,  301,  301,  302,  302,  302,  302,  281,  320,  320,
      320,  320,  155,  306,  306,  306,  306,  329,  329,  265,
      329,  329,  329,  267,  155,  329,  329,  157,  321,  305,
      305,  305,  305,  307,  322,  322,  322,  322,  308,  308,
      308,  308,  268,  280,  309,  309,  309,  309,  264,  269,
      329,  279,  329,  329,  268,  329,  329,  279,  273,  323,
      323,  323,  323,  279,  273,  320,  320,  320,  320,  279,
      326,  326,  326,  326,  322,  322,  322,  322,  228,  324,
      323,  323,  323,  323,  224,  321,  327,  327,  327,  327,
      326,  326,  326,  326,  307,  327,  327,  327,  327,  211,

      324,  329,  329,  329,  329,  329,  169,  168,  167,  153,
      321,  152,  151,  132,  130,  324,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   72,
      329,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       96,   95,   88,   96,   96,   97,   81,   97,   78,   97,
       97,  100,  100,   77,  100,   74,  100,  100,  131,  131,
       73,  131,  131,  131,  131,  131,   71,  131,  131,  148,
      148,  148,  329,  148,  148,  148,  148,  329,  148,  148,

      163,  329,  329,  329,  329,  163,  170,  170,  171,  329,
      171,  329,  171,  171,  210,  329,  329,  329,  329,  210,
      229,  329,  229,  329,  229,  229,  263,  329,  329,  329,
      329,  263,  276,  329,  329,  329,  329,  276,    9,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329
    } ;

static yyconst short int yy_chk[1006] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    5,    4,
        4,    6,   20,    7,  103,   24,    8,   24,   24,   24,
       24,   30,   30,   32,   32,   20,   27,   31,   27,   27,
       27,   27,   41,   51,    5,    7,    3,    6,    8,    4,

      103,   27,   31,   40,   50,   48,  319,   39,   27,   39,
       39,   39,   39,   27,   43,   42,   84,   84,   44,   41,
       51,  221,  221,   52,   45,    3,   54,    3,    4,   39,
        4,   26,   41,   26,   26,   26,   26,   40,   42,   40,
       47,   43,   48,   49,   50,   26,   26,   45,   26,   42,
       52,   43,   44,   26,   44,   26,   53,   44,   26,   55,
       56,   45,   54,   68,  102,  104,   52,   68,   47,  107,
       49,  318,  105,  106,   49,  108,   47,   26,  317,  113,
       49,  110,  111,  117,  118,  114,   53,  316,  125,   55,
      124,   56,  107,   68,  104,  102,   53,   64,   64,  105,

      112,   64,   80,  108,   80,   80,   80,   80,  111,  117,
       64,   64,   64,  113,  106,  125,   82,   80,   82,   82,
       82,   82,  110,  111,   80,  114,  119,   64,  124,   80,
      118,   64,   64,  123,  112,   64,   64,  314,   82,   85,
      126,   85,  180,  112,   64,   85,   85,   85,   64,   64,
       64,  120,   64,   83,   64,   83,   83,   83,   83,   87,
      119,   87,   87,   87,   87,  122,  127,  123,   83,   98,
       98,   98,   98,  180,   99,   83,   99,   99,   99,   99,
       83,   87,  101,  126,  101,  101,  101,  101,  128,   98,
      129,  122,  127,  120,  300,  178,   99,  136,  136,  136,

      127,  161,  161,  161,  101,  181,  122,  122,  127,  154,
      154,  154,  154,  183,  155,  128,  155,  129,  178,  128,
      155,  155,  155,  156,  156,  156,  156,  157,  181,  157,
      157,  157,  157,  158,  182,  158,  158,  158,  158,  159,
      159,  159,  159,  160,  160,  188,  289,  199,  158,  162,
      162,  162,  162,  241,  183,  158,  188,  289,  184,  159,
      158,  182,  190,  160,  164,  164,  164,  164,  165,  162,
      165,  165,  165,  165,  166,  199,  166,  166,  166,  166,
      187,  241,  192,  165,  164,  172,  172,  172,  172,  184,
      165,  173,  173,  173,  173,  165,  166,  174,  174,  174,

      174,  189,  185,  190,  175,  172,  175,  175,  175,  175,
      176,  173,  176,  176,  176,  176,  193,  174,  177,  177,
      177,  177,  196,  187,  189,  192,  175,  197,  198,  185,
      200,  201,  176,  185,  202,  203,  204,  206,  177,  205,
      207,  208,  209,  209,  209,  213,  213,  213,  217,  325,
      217,  250,  197,  234,  217,  217,  217,  200,  193,  196,
      325,  202,  203,  204,  236,  244,  299,  201,  198,  242,
      205,  198,  235,  206,  207,  208,  212,  212,  212,  212,
      214,  214,  214,  214,  223,  223,  223,  223,  215,  212,
      215,  215,  215,  215,  234,  238,  212,  236,  250,  244,

      214,  212,  216,  215,  216,  216,  216,  216,  235,  242,
      215,  218,  218,  218,  218,  215,  245,  216,  219,  219,
      219,  219,  249,  298,  216,  220,  220,  220,  220,  216,
      296,  218,  222,  222,  222,  222,  238,  239,  219,  225,
      225,  225,  225,  245,  295,  220,  226,  226,  226,  226,
      251,  253,  222,  227,  246,  227,  227,  227,  227,  225,
      257,  230,  230,  230,  230,  249,  226,  256,  227,  231,
      231,  231,  231,  239,  258,  227,  232,  232,  232,  232,
      227,  230,  233,  233,  233,  233,  260,  293,  246,  231,
      251,  253,  261,  313,  290,  256,  232,  265,  265,  265,

      265,  257,  233,  266,  266,  266,  266,  297,  258,  267,
      267,  267,  267,  260,  268,  287,  268,  285,  261,  313,
      268,  268,  268,  266,  269,  269,  269,  269,  270,  270,
      270,  271,  271,  271,  271,  272,  286,  272,  272,  272,
      272,  273,  273,  273,  273,  274,  274,  284,  297,  283,
      272,  271,  275,  275,  275,  275,  294,  272,  303,  303,
      303,  273,  272,  286,  288,  274,  277,  277,  277,  277,
      291,  292,  275,  278,  278,  278,  278,  279,  282,  279,
      310,  310,  310,  279,  279,  279,  277,  281,  281,  281,
      281,  288,  294,  278,  280,  276,  259,  291,  292,  301,

      301,  301,  301,  302,  302,  302,  302,  281,  304,  304,
      304,  304,  301,  306,  306,  306,  306,  255,  254,  301,
      252,  248,  247,  302,  301,  240,  237,  305,  304,  305,
      305,  305,  305,  306,  307,  307,  307,  307,  308,  308,
      308,  308,  305,  228,  309,  309,  309,  309,  211,  305,
      195,  308,  194,  191,  305,  186,  179,  309,  308,  311,
      311,  311,  311,  308,  309,  320,  320,  320,  320,  309,
      321,  321,  321,  321,  322,  322,  322,  322,  169,  311,
      323,  323,  323,  323,  163,  320,  324,  324,  324,  324,
      326,  326,  326,  326,  322,  327,  327,  327,  327,  151,

      323,  121,  116,  115,  109,  100,   92,   91,   90,   79,
      326,   75,   70,   63,   58,  327,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  332,  332,
      332,  332,  332,  332,  332,  332,  332,  332,  332,  333,
       46,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      334,   34,   28,  334,  334,  335,   25,  335,   23,  335,
      335,  336,  336,   21,  336,   16,  336,  336,  337,  337,
       15,  337,  337,  337,  337,  337,   12,  337,  337,  338,
      338,  338,    9,  338,  338,  338,  338,    0,  338,  338,

      339,    0,    0,    0,    0,  339,  340,  340,  341,    0,
      341,    0,  341,  341,  342,    0,    0,    0,    0,  342,
      343,    0,  343,    0,  343,  343,  344,    0,    0,    0,
        0,  344,  345,    0,    0,    0,    0,  345,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#line 5 "lexer.l"
	#include <stdio.h>
    #include <stdlib.h>
    #include <string.h>

    char* removeUnderscores(const char* input) {
    char* result = malloc(strlen(input) + 1);
    int resultIndex = 0;
    
    for (int i = 0; input[i]; i++) {
        if (input[i] != '_') {
            result[resultIndex++] = input[i];
        }
    }
    
    result[resultIndex] = '\0';
    return result;
}

#define DOUBLE_QUOTE_STRING 1

#define SINGLE_QUOTE_STRING 2

#define ML_COMMENT 3

#line 725 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 40 "lexer.l"

#line 874 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 330 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 939 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 41 "lexer.l"
{ printf("Error: Underscore at the start of a number: %s\n", yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "lexer.l"
{ printf("Error: Underscore at the end of a number: %s\n", yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "lexer.l"
{ printf("Error: Underscore before point: %s\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "lexer.l"
{ printf("Error: Underscore after point: %s\n", yytext); }
	YY_BREAK

    int num;
    int doubleQuote;
    char temp1[100];
    char string[1000];
    int nestingCount = 0;

case 5:
YY_RULE_SETUP
#line 55 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 56 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 57 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 69 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 77 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 78 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 79 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 80 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 81 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 82 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 83 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 84 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 85 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 86 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 87 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 88 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 89 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 90 "lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 92 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }   
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 93 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 94 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 95 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 96 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 97 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 99 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 100 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 101 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 102 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 103 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 104 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 105 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 106 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 107 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 108 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 110 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 111 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 112 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 113 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 114 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 115 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 116 "lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 118 "lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 119 "lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 120 "lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 121 "lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 122 "lexer.l"
{ printf("Found comparison operation: %s\n", yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 123 "lexer.l"
{ printf("Found comparison operation: %s\n", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 125 "lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 126 "lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 127 "lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 129 "lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 130 "lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 132 "lexer.l"
{ printf("Found bracket: %s\n", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 133 "lexer.l"
{ printf("Found bracket: %s\n", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 134 "lexer.l"
{ printf("Found bracket: %s\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 135 "lexer.l"
{
                if(nestingCount == 0) {
                    printf("Found bracket: %s\n", yytext);
                } else {
                    nestingCount--;
                    BEGIN(DOUBLE_QUOTE_STRING);
                    string[0] = 0;
                    printf("Found interpolation: +\n");
                }
            }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 145 "lexer.l"
{ printf("Found bracket: %s\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 146 "lexer.l"
{ printf("Found bracket: %s\n", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 148 "lexer.l"
{ printf("Found question symbol: %s\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 150 "lexer.l"
{ printf("Found special symbol: %s\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 151 "lexer.l"
{ printf("Found special symbol: %s\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 152 "lexer.l"
{ printf("Found special symbol: %s\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 153 "lexer.l"
{ printf("Found special symbol: %s\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 154 "lexer.l"
{ printf("Found special symbol: %s\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 155 "lexer.l"
{ printf("Found line feed: %s\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 157 "lexer.l"
{
                string[0] = '\0'; 
                BEGIN(DOUBLE_QUOTE_STRING);
            }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 162 "lexer.l"
{
                string[0] = '\0'; 
                BEGIN(SINGLE_QUOTE_STRING);    
            }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 168 "lexer.l"
{ printf("Found identifier: %s\n", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 170 "lexer.l"
{printf("Found method name: %s\n", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 171 "lexer.l"
{printf("Found class name: %s\n", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 172 "lexer.l"
{printf("Found var name: %s\n", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 173 "lexer.l"
{printf("Found class var name: %s\n", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 174 "lexer.l"
{printf("Found constant: %s\n", yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 176 "lexer.l"
{ 
                                printf("Found string \"%s\"\n", string);
                                printf("Found interpolation: +\n");
                                nestingCount++;
                                BEGIN(INITIAL);
                            }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 183 "lexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 184 "lexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 185 "lexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 186 "lexer.l"
{ strcat(string, "\\'"); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 187 "lexer.l"
{ strcat(string, "\n"); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 188 "lexer.l"
{ strcat(string, "\a"); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 189 "lexer.l"
{ strcat(string, "\b"); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 190 "lexer.l"
{ strcat(string, "\t"); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 191 "lexer.l"
{ strcat(string, "\v"); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 192 "lexer.l"
{ strcat(string, "\f"); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 193 "lexer.l"
{ strcat(string, "\r"); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 194 "lexer.l"
{ strcat(string, "\e"); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 195 "lexer.l"
{ strcat(string, " "); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 196 "lexer.l"
{ strcat(string, "\\");}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 197 "lexer.l"
{ strcat(string, "\""); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 198 "lexer.l"
{ strcat(string, "#"); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 201 "lexer.l"
{ strcat(string, "\\\""); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 202 "lexer.l"
{ strcat(string, "'"); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 206 "lexer.l"
{ 
                                sscanf(yytext + 1, "%o", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 213 "lexer.l"
{ 
                                sscanf(yytext + 2, "%x", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 220 "lexer.l"
{ 
                                printf("String literal: \"%s\" \n", string);
                                BEGIN(INITIAL);
                        }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 225 "lexer.l"
{ 
                            printf("String literal: \"%s\" \n", string);
                            BEGIN(INITIAL);
                        }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 231 "lexer.l"
{ printf("Found single-line comment: %s\n", yytext + 1); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 235 "lexer.l"
{
    BEGIN(ML_COMMENT);
    printf("Found multiline comment:\n");
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 240 "lexer.l"
{
    BEGIN(INITIAL);
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 245 "lexer.l"
{
    printf("%s", yytext);
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 251 "lexer.l"
{ 
    
    char* cleanedText = removeUnderscores(yytext);
    int number = atoi(cleanedText);
    printf("Found integer: %d\n", number); 
    free(cleanedText); 
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 258 "lexer.l"
{ 
    char* cleanedText = removeUnderscores(yytext);
    int number = strtol(cleanedText, NULL, 16);
    printf("Found hexadecimal integer: %d\n", number); 
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 264 "lexer.l"
{
    char* cleanedText = removeUnderscores(yytext + 2);
    int number = strtol( cleanedText, NULL, 2);
    printf("Found binary integer: %d\n", yytext);
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 270 "lexer.l"
{ 
    char* cleanedText = removeUnderscores(yytext);
    double number = atof(cleanedText);
    printf("Found floating-point number: %f\n", number); 
}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 276 "lexer.l"
{ 
    char* cleanedText = removeUnderscores(yytext);
    double number = atof(cleanedText);
    printf("Found floating-point number with exponent: %f\n", number); 
}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 282 "lexer.l"
{
    char* cleanedText = removeUnderscores(yytext);
    double number = atof(cleanedText);
    printf("Found number with exponent: %f\n", number); 
}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 288 "lexer.l"
{
    printf("Error: Underscore is repeated several times in a row: %s\n", yytext); 
}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 292 "lexer.l"
{printf("Error: Dot at the start of a number: %s\n", yytext); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 294 "lexer.l"
{printf("Error: Dot is repeated several times in a row: %s\n", yytext); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 297 "lexer.l"
ECHO;
	YY_BREAK
#line 1695 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DOUBLE_QUOTE_STRING):
case YY_STATE_EOF(SINGLE_QUOTE_STRING):
case YY_STATE_EOF(ML_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 330 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 330 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 329);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 297 "lexer.l"


int main(int argc, char** argv) {
    if (argc != 2) {
        printf("You need to specify file name");
        return 1;
    }

    const char *filename = argv[1];
    
    FILE *file = fopen(filename, "r");
    if (file == NULL) {
        printf("File opening error");
        return 1;
    }

    yyin = file;

    while (yylex() != 0);

    fclose(file);

    return 0;
}

