/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 131
#define YY_END_OF_BUFFER 132
static yyconst short int yy_accept[338] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  132,  131,
       87,   72,   88,  117,   45,   64,   89,   75,   76,   43,
       41,   83,   42,   82,   44,  120,  120,   84,   86,   50,
       57,   49,   81,  131,   90,   79,   80,   66,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   77,   65,   78,   67,
       96,  115,   97,  131,   95,  116,  131,  131,  131,   48,
      117,   62,   70,   46,   60,   58,   59,   73,  129,   61,
      123,  120,    0,    0,    0,    2,   85,   68,   52,   47,
        0,   51,   69,    0,   92,   90,    0,    1,   91,    1,

       91,   91,   91,   91,   91,   91,   91,   13,   91,   91,
       91,   91,   91,   14,   21,   91,   91,   91,   91,   26,
       91,   91,   91,   91,   91,   91,   91,   91,   71,   96,
       94,  109,  110,   98,  113,  108,  100,  101,  106,  104,
       99,  105,  107,  102,  103,    0,   95,  111,  112,    0,
        0,    0,   63,   74,    0,    0,    0,    0,  123,    2,
      122,    0,  125,  121,    0,  120,    2,   53,   54,    0,
       93,   92,    0,    2,    1,    1,    1,    1,    1,   91,
        6,   91,   91,   91,   91,   11,   91,   17,   91,   91,
       91,   91,   20,   91,   91,   24,   25,   91,   91,   91,

       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
      113,  114,    0,  129,    0,  129,  129,  130,    0,    2,
        4,    2,    0,  125,    0,    0,    3,    2,  126,    0,
       93,    1,    1,    1,    1,   91,   91,   91,    9,   91,
       91,   15,   91,   91,   55,   91,   91,   91,   23,   27,
       91,   91,   91,   31,   91,   33,   34,   91,   91,   91,
       38,   91,   91,  113,  114,    0,    0,  129,    0,    0,
        0,    0,  124,  123,    2,  122,    0,  125,  121,    0,
        2,    0,    0,    0,    1,    5,    7,    8,   10,   91,
       16,   91,   91,   19,   91,   91,   29,   91,   32,   35,

       91,   37,   39,   40,  119,  119,  129,  129,    0,  130,
      130,  124,    0,  126,  128,  127,  126,    0,  126,  118,
       91,   18,   56,   22,   28,   30,   36,  130,    0,  124,
      126,    0,   91,  130,  126,   12,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   28,   28,   30,   28,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   32,   31,   31,
       33,   34,   35,   36,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   47,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[67] =
    {   0,
        1,    2,    1,    3,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    1,    6,    6,    6,    6,
        1,    1,    1,    1,    1,    1,    7,    6,    6,    6,
        8,    8,    1,    9,    1,    1,   10,   11,   11,   11,
       11,   11,   11,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[356] =
    {   0,
        0,    0,   63,   65,   64,   66,   69,   71,  847, 1011,
     1011,  822, 1011,    0,  821,  837, 1011, 1011, 1011,   64,
      819, 1011,  818,   61,  808,   86,   72,  810, 1011,   59,
       72,   60, 1011,  803,    0, 1011, 1011, 1011,  102,   92,
       71,   93,  109,   95,  112,  813,   97,  114,  117,   79,
      115,  118,  120,  121,  122,  137, 1011,  763, 1011, 1011,
        0, 1011,  763,  180,    0, 1011,  166,  800,  114, 1011,
        0, 1011, 1011,  799, 1011, 1011, 1011,  807,  174, 1011,
      188,  225,  136,  159,    0,  209, 1011, 1011,  774,  774,
      755, 1011, 1011,    0,    0,    0,  231,  239,  779,  246,

      140,  172,  165,  153,  197,  143,  147,  778,  215,  219,
      223,  237,  218,  777,  775,  206,  217,  254,  255,  774,
      259,  262,  167,  264,  265,  269,  267,  272, 1011,    0,
     1011, 1011, 1011, 1011,  271, 1011, 1011, 1011, 1011, 1011,
     1011, 1011, 1011, 1011, 1011,    0,    0, 1011, 1011,  763,
      275,  268, 1011, 1011,  276,  310,  314,  320,  326,  330,
      284,  333,  340,  749,  352,  361,  367, 1011, 1011,  741,
        0,    0,  375,  382,  388,  396,  403,  409,  417,  270,
      749,  290,  282,  283,  327,  350,  402,  748,  339,  340,
      289,  375,  741,  394,  373,  740,  736,  358,  409,  423,

      424,  426,  428,  427,  430,  432,  436,  435,  438,  440,
      439,    0,  435,  443,  446,  473,  479,  485,  494,  500,
      506,  511,  515,  521,  527,  713,  536,  542,  548,  698,
        0,  552,  557,  563,  578,  455,  456,  486,  713,  480,
      535,  689,  549,  536, 1011,  569,  572,  573,  675,  644,
      578,  473,  584,  635,  586,  627,  622,  587,  588,  589,
      614,  590,  592, 1011, 1011,  604,  591,  606,  628,  637,
      644,  601,  648,  654,  658,  617,  662,  669,  590,  580,
      683,  690,  699,  506,  704,  534,  527,  469,  468,  598,
      462,  616,  349,  460,  655,  683,  359,  601,  347,  346,

      597,  292,  276,  202, 1011,  191,  712,  716,  663,  720,
      728,  742,  749,  754,  675,  173,  758,  696,  784, 1011,
      711,  187, 1011,  186,  181,  130,   62,  788,  763,  792,
      796,  800,  679,  817,  821, 1011, 1011,  858,  870,  882,
      894,  900,  907,  915,  927,  939,  951,  958,  960,  967,
      974,  980,  987,  993,  999
    } ;

static yyconst short int yy_def[356] =
    {   0,
      337,    1,  338,  338,  339,  339,  340,  340,  337,  337,
      337,  337,  337,  341,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  342,  343,  337,  337,  337,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  337,  337,  337,  337,
      345,  337,  337,  337,  346,  337,  337,  347,  347,  337,
      341,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  348,  337,  337,  337,  337,  337,
      337,  337,  337,  349,  350,  343,  337,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  337,  345,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  351,  346,  337,  337,  347,
      347,  347,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  348,  337,  337,  337,  337,  337,  337,
      352,  350,  337,  337,  337,  344,  344,  337,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      337,  353,  347,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  354,  337,  337,  337,  337,
      352,  337,  337,  337,  337,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  337,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  337,  337,  347,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  354,  355,
      337,  337,  337,  337,  337,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  337,  347,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  355,  337,  337,  337,  337,
      344,  344,  337,  344,  344,  344,  344,  337,  337,  337,
      337,  337,  344,  337,  337,  337,    0,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337
    } ;

static yyconst short int yy_nxt[1078] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   27,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   35,   35,
       35,   35,   36,   10,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   46,   47,   46,   46,   46,   48,
       49,   50,   46,   46,   51,   52,   53,   54,   46,   55,
       46,   56,   57,   58,   59,   60,   62,   63,   62,   63,
       10,   66,   10,   66,   74,   78,  337,   79,   79,   79,
       79,   88,   89,   92,   93,  337,   81,   75,   82,   82,
       82,   82,   69,  337,   69,   90,   64,   67,   64,   67,

       81,   84,   82,   82,   82,   82,  337,  337,   86,  337,
       91,  337,  103,   84,   83,   84,   97,   85,   98,   98,
       98,   98,   86,  337,   83,  104,  337,   84,  337,  337,
      105,  337,  337,  120,  337,  337,  337,  151,  100,  114,
      101,  106,  102,  109,  337,  110,   85,  115,  111,  112,
      107,  337,  161,  161,  337,  152,  121,  337,  117,  122,
      108,  337,  118,  113,  124,  116,  127,  337,  119,  148,
      162,  126,  162,  149,  125,  123,  163,  163,  163,  337,
      185,  337,  128,  132,  133,  180,  337,  134,  155,  186,
       79,   79,   79,   79,  183,  337,  135,  135,  135,  136,

      337,  337,  158,  156,  159,  159,  159,  159,  182,  280,
      157,  337,  181,  136,  151,  156,  337,  137,  138,  202,
      337,  139,  140,  165,  160,  166,  166,  166,  166,  337,
      141,  337,  337,  337,  142,  143,  144,  337,  145,   81,
      146,   82,   82,   82,   82,  167,  194,  173,  173,  173,
      173,  337,  184,  175,   84,  176,  176,  176,  176,  188,
      178,   86,  176,  176,  176,  176,   84,  174,  337,  337,
      187,  190,  193,  337,  189,  177,  337,  195,  337,  337,
      191,  337,  179,  337,  337,  192,  337,  211,  211,  211,
      337,  151,  214,  214,  214,  214,  337,  337,  151,  198,

      161,  161,  196,  337,  337,  203,  337,  236,  208,  205,
      201,  197,  209,  210,  199,  200,  152,  206,  213,  238,
      223,  215,  204,  215,  239,  207,  246,  216,  216,  216,
      217,  217,  217,  217,  158,  237,  218,  218,  218,  218,
      158,  337,  159,  159,  159,  159,  221,  221,  221,  221,
      163,  163,  163,  337,  337,  219,  224,  224,  224,  224,
      337,  337,  220,  337,  337,  245,  222,  219,  227,  227,
      227,  227,  337,  337,  323,   81,  225,  166,  166,  166,
      166,  165,  240,  229,  229,  229,  229,  337,  228,  337,
       84,  173,  173,  173,  173,  241,  244,   86,  173,  173,

      173,  173,   84,  167,  232,  232,  232,  232,  337,  250,
      175,  174,  176,  176,  176,  176,  337,  178,  174,  176,
      176,  176,  176,  337,  233,  234,  234,  234,  234,  249,
      247,  178,  177,  176,  176,  176,  176,  337,  337,  177,
      337,  337,  337,  242,  337,  235,  337,  243,  251,  337,
      337,  248,  337,  179,  337,  264,  264,  264,  151,  214,
      214,  214,  214,  216,  216,  216,  254,  255,  257,  337,
      337,  258,  156,  259,  337,  266,  337,  252,  256,  267,
      253,  260,  337,  337,  156,  261,  262,  337,  263,  268,
      268,  268,  268,  155,  337,  217,  217,  217,  217,  158,

      337,  218,  218,  218,  218,  272,  287,  272,  156,  269,
      286,  273,  273,  273,  270,  157,  274,  274,  274,  274,
      156,  271,  221,  221,  221,  221,  270,  221,  221,  221,
      221,  276,  276,  288,  297,  289,  275,  224,  224,  224,
      224,  337,  222,  278,  278,  278,  278,  222,  337,  337,
      337,  277,  227,  227,  227,  227,  320,  225,  227,  227,
      227,  227,  282,  337,  229,  229,  229,  229,  232,  232,
      232,  232,  281,  232,  232,  232,  232,  283,  281,  234,
      234,  234,  234,  337,  167,  290,  337,  337,  233,  283,
      292,  291,  337,  233,  234,  234,  234,  234,  337,  285,

      337,  337,  337,  337,  337,  305,  337,  307,  307,  307,
      307,  337,  337,  294,  285,  337,  280,  293,  273,  273,
      273,  295,  268,  268,  268,  268,  226,  151,  337,  300,
      337,  303,  304,  276,  276,  296,  337,  302,  298,  321,
      299,  337,  269,  301,  308,  308,  308,  308,  309,  337,
      309,  326,  327,  223,  310,  310,  310,  322,  337,  306,
      311,  311,  311,  311,  312,  312,  312,  312,  158,  337,
      274,  274,  274,  274,  314,  314,  314,  314,  315,  315,
      310,  310,  310,  219,  313,  278,  278,  278,  278,  337,
      220,  315,  315,  337,  275,  219,  324,  337,  277,  227,

      227,  227,  227,  337,  336,  225,  317,  317,  317,  317,
      318,  277,  318,  319,  319,  319,  319,  319,  319,  281,
      234,  234,  234,  234,  325,  337,  174,  337,  307,  307,
      307,  307,  308,  308,  308,  308,  328,  328,  328,  328,
      285,  156,  158,  284,  311,  311,  311,  311,  267,  280,
      337,  333,  269,  156,  337,  337,  329,  270,  312,  312,
      312,  312,  337,  337,  271,  330,  330,  330,  330,  270,
      314,  314,  314,  314,  317,  317,  317,  317,  313,  334,
      334,  334,  334,  283,  230,  226,  151,  283,  337,  337,
      275,  337,  337,  337,  275,  283,  170,  169,  168,  283,

      331,  331,  331,  331,  328,  328,  328,  328,  330,  330,
      330,  330,  331,  331,  331,  331,  335,  335,  335,  335,
      332,  154,  153,  151,  329,  131,  129,  337,  313,   94,
       87,   80,  332,  334,  334,  334,  334,  335,  335,  335,
      335,   77,   76,   73,   72,   70,  337,  337,  337,  337,
      337,  337,  337,  329,  337,  337,  337,  332,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   71,  337,   71,   71,   71,   71,

       71,   71,   71,   71,   71,   71,   95,  337,  337,   95,
       95,   95,   96,  337,   96,  337,   96,   96,   96,   99,
       99,  337,   99,  337,   99,   99,   99,  130,  130,  337,
      130,  130,  130,  130,  130,  337,  130,  130,  130,  147,
      147,  147,  337,  147,  147,  147,  147,  337,  147,  147,
      147,  150,  337,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  164,  337,  337,  337,  337,  164,  171,
      171,  171,  172,  337,  172,  337,  172,  172,  172,  212,
      337,  337,  337,  337,  212,  231,  337,  231,  337,  231,
      231,  231,  265,  337,  337,  337,  337,  265,  279,  337,

      337,  337,  279,  279,  316,  337,  337,  337,  316,  316,
        9,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337
    } ;

static yyconst short int yy_chk[1078] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    4,    4,
        7,    5,    8,    6,   20,   24,  327,   24,   24,   24,
       24,   30,   30,   32,   32,   41,   27,   20,   27,   27,
       27,   27,    7,   50,    8,   31,    3,    5,    4,    6,

       26,   27,   26,   26,   26,   26,   40,   42,   27,   44,
       31,   47,   41,   27,   26,   26,   39,   26,   39,   39,
       39,   39,   26,   43,   26,   41,   45,   26,   48,   51,
       42,   49,   52,   50,   53,   54,   55,   69,   39,   47,
       40,   42,   40,   44,  326,   44,   26,   47,   44,   45,
       43,   56,   83,   83,  101,   69,   51,  106,   49,   52,
       43,  107,   49,   45,   53,   48,   55,  104,   49,   67,
       84,   54,   84,   67,   53,   52,   84,   84,   84,  103,
      106,  123,   56,   64,   64,  101,  102,   64,   79,  107,
       79,   79,   79,   79,  104,  325,   64,   64,   64,   67,

      324,  322,   81,   79,   81,   81,   81,   81,  103,  316,
       79,  105,  102,   64,  306,   79,  304,   64,   64,  123,
      116,   64,   64,   86,   81,   86,   86,   86,   86,  109,
       64,  117,  113,  110,   64,   64,   64,  111,   64,   82,
       64,   82,   82,   82,   82,   86,  116,   97,   97,   97,
       97,  112,  105,   98,   82,   98,   98,   98,   98,  110,
      100,   82,  100,  100,  100,  100,   82,   97,  118,  119,
      109,  111,  113,  121,  110,   98,  122,  117,  124,  125,
      111,  127,  100,  126,  180,  112,  128,  135,  135,  135,
      303,  152,  155,  155,  155,  155,  183,  184,  151,  121,

      161,  161,  118,  191,  182,  124,  302,  180,  127,  126,
      122,  119,  127,  128,  121,  121,  151,  126,  152,  183,
      161,  156,  125,  156,  184,  126,  191,  156,  156,  156,
      157,  157,  157,  157,  158,  182,  158,  158,  158,  158,
      159,  185,  159,  159,  159,  159,  160,  160,  160,  160,
      162,  162,  162,  189,  190,  159,  163,  163,  163,  163,
      300,  299,  159,  293,  186,  190,  160,  159,  165,  165,
      165,  165,  198,  297,  293,  166,  163,  166,  166,  166,
      166,  167,  185,  167,  167,  167,  167,  195,  165,  192,
      166,  173,  173,  173,  173,  186,  189,  166,  174,  174,

      174,  174,  166,  167,  175,  175,  175,  175,  194,  198,
      176,  173,  176,  176,  176,  176,  187,  177,  174,  177,
      177,  177,  177,  199,  175,  178,  178,  178,  178,  195,
      192,  179,  176,  179,  179,  179,  179,  200,  201,  177,
      202,  204,  203,  187,  205,  178,  206,  187,  199,  208,
      207,  194,  209,  179,  210,  211,  211,  211,  213,  214,
      214,  214,  214,  215,  215,  215,  201,  202,  204,  236,
      237,  205,  214,  206,  294,  213,  291,  200,  203,  214,
      200,  207,  289,  288,  214,  208,  209,  252,  210,  216,
      216,  216,  216,  217,  240,  217,  217,  217,  217,  218,

      238,  218,  218,  218,  218,  219,  237,  219,  217,  216,
      236,  219,  219,  219,  218,  217,  220,  220,  220,  220,
      217,  218,  221,  221,  221,  221,  218,  222,  222,  222,
      222,  223,  223,  238,  252,  240,  220,  224,  224,  224,
      224,  287,  221,  225,  225,  225,  225,  222,  286,  241,
      244,  223,  227,  227,  227,  227,  284,  224,  228,  228,
      228,  228,  229,  243,  229,  229,  229,  229,  232,  232,
      232,  232,  227,  233,  233,  233,  233,  229,  228,  234,
      234,  234,  234,  246,  229,  241,  247,  248,  232,  229,
      244,  243,  251,  233,  235,  235,  235,  235,  253,  234,

      255,  258,  259,  260,  262,  266,  263,  267,  267,  267,
      267,  301,  290,  247,  235,  298,  280,  246,  272,  272,
      272,  248,  268,  268,  268,  268,  279,  266,  261,  258,
      292,  262,  263,  276,  276,  251,  257,  260,  253,  290,
      255,  256,  268,  259,  269,  269,  269,  269,  270,  254,
      270,  298,  301,  276,  270,  270,  270,  292,  250,  266,
      271,  271,  271,  271,  273,  273,  273,  273,  274,  295,
      274,  274,  274,  274,  275,  275,  275,  275,  277,  277,
      309,  309,  309,  274,  273,  278,  278,  278,  278,  249,
      274,  315,  315,  333,  275,  274,  295,  296,  277,  281,

      281,  281,  281,  242,  333,  278,  282,  282,  282,  282,
      283,  315,  283,  318,  318,  318,  283,  283,  283,  281,
      285,  285,  285,  285,  296,  321,  282,  239,  307,  307,
      307,  307,  308,  308,  308,  308,  310,  310,  310,  310,
      285,  307,  311,  230,  311,  311,  311,  311,  307,  226,
      197,  321,  308,  307,  196,  193,  310,  311,  312,  312,
      312,  312,  188,  181,  311,  313,  313,  313,  313,  311,
      314,  314,  314,  314,  317,  317,  317,  317,  312,  329,
      329,  329,  329,  314,  170,  164,  150,  317,  120,  115,
      314,  114,  108,   99,  317,  314,   91,   90,   89,  317,

      319,  319,  319,  319,  328,  328,  328,  328,  330,  330,
      330,  330,  331,  331,  331,  331,  332,  332,  332,  332,
      319,   78,   74,   68,  328,   63,   58,   46,  330,   34,
       28,   25,  331,  334,  334,  334,  334,  335,  335,  335,
      335,   23,   21,   16,   15,   12,    9,    0,    0,    0,
        0,    0,    0,  334,    0,    0,    0,  335,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      339,  339,  339,  339,  339,  339,  339,  339,  339,  339,
      339,  339,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  341,    0,  341,  341,  341,  341,

      341,  341,  341,  341,  341,  341,  342,    0,    0,  342,
      342,  342,  343,    0,  343,    0,  343,  343,  343,  344,
      344,    0,  344,    0,  344,  344,  344,  345,  345,    0,
      345,  345,  345,  345,  345,    0,  345,  345,  345,  346,
      346,  346,    0,  346,  346,  346,  346,    0,  346,  346,
      346,  347,    0,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  348,    0,    0,    0,    0,  348,  349,
      349,  349,  350,    0,  350,    0,  350,  350,  350,  351,
        0,    0,    0,    0,  351,  352,    0,  352,    0,  352,
      352,  352,  353,    0,    0,    0,    0,  353,  354,    0,

        0,    0,  354,  354,  355,    0,    0,    0,  355,  355,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 ".\\lexer.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#line 5 ".\\lexer.l"
	#include <stdio.h>
    #include <stdlib.h>
    #include <string.h>

    char* removeUnderscores(const char* input);

#define DOUBLE_QUOTE_STRING 1

#define SINGLE_QUOTE_STRING 2

#define ML_COMMENT 3

#line 730 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 28 ".\\lexer.l"



    int num;
    int doubleQuote;
    char temp1[100];
    char string[1000];
    int nestingCount = 0;


#line 888 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 338 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1011 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 38 ".\\lexer.l"
{ printf("Error: Underscore at the start of a number: %s\n", yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 ".\\lexer.l"
{ printf("Error: Underscore at the end of a number: %s\n", yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 ".\\lexer.l"
{ printf("Error: Underscore right before point: %s\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 ".\\lexer.l"
{ printf("Error: Underscore right after point: %s\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 68 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 69 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 72 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 73 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 ".\\lexer.l"
{ printf("Found keyword: %s\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }   
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 88 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 89 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 90 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 91 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 93 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 94 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 95 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 96 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 97 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 102 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 103 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 104 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 105 ".\\lexer.l"
{ printf("Found arithmetic operation: %s\n", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 ".\\lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 ".\\lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 ".\\lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 ".\\lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 ".\\lexer.l"
{ printf("Found comparison operation: %s\n", yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 ".\\lexer.l"
{ printf("Found comparison operation: %s\n", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 114 ".\\lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 115 ".\\lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 116 ".\\lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 118 ".\\lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 119 ".\\lexer.l"
{ printf("Found operation: %s\n", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 121 ".\\lexer.l"
{ printf("Found bracket: %s\n", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 122 ".\\lexer.l"
{ printf("Found bracket: %s\n", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 123 ".\\lexer.l"
{ printf("Found bracket: %s\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 124 ".\\lexer.l"
{
                if(nestingCount == 0) {
                    printf("Found bracket: %s\n", yytext);
                } else {
                    nestingCount--;
                    BEGIN(DOUBLE_QUOTE_STRING);
                    string[0] = 0;
                    printf("Found interpolation: ) + \n");
                }
            }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 134 ".\\lexer.l"
{ printf("Found bracket: %s\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 135 ".\\lexer.l"
{ printf("Found bracket: %s\n", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 137 ".\\lexer.l"
{ printf("Found question symbol: %s\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 139 ".\\lexer.l"
{ printf("Found special symbol: %s\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 140 ".\\lexer.l"
{ printf("Found special symbol: %s\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 141 ".\\lexer.l"
{ printf("Found special symbol: %s\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 142 ".\\lexer.l"
{ printf("Found special symbol: %s\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 143 ".\\lexer.l"
{ printf("Found special symbol: %s\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 144 ".\\lexer.l"
{ printf("Found line feed: %s\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 146 ".\\lexer.l"
{
                string[0] = '\0'; 
                BEGIN(DOUBLE_QUOTE_STRING);
            }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 151 ".\\lexer.l"
{
                string[0] = '\0'; 
                BEGIN(SINGLE_QUOTE_STRING);    
            }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 159 ".\\lexer.l"
{printf("Found constant: %s\n", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 161 ".\\lexer.l"
{ printf("Found identifier: %s\n", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 162 ".\\lexer.l"
{printf("Found var name: %s\n", yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 163 ".\\lexer.l"
{printf("Found class var name: %s\n", yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 165 ".\\lexer.l"
{ 
                                printf("Found string \"%s\"\n", string);
                                printf("Found interpolation: + ( \n");
                                nestingCount++;
                                BEGIN(INITIAL);
                            }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 172 ".\\lexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 173 ".\\lexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 174 ".\\lexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 175 ".\\lexer.l"
{ strcat(string, "\\'"); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 176 ".\\lexer.l"
{ strcat(string, "\n"); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 177 ".\\lexer.l"
{ strcat(string, "\a"); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 178 ".\\lexer.l"
{ strcat(string, "\b"); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 179 ".\\lexer.l"
{ strcat(string, "\t"); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 180 ".\\lexer.l"
{ strcat(string, "\v"); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 181 ".\\lexer.l"
{ strcat(string, "\f"); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 182 ".\\lexer.l"
{ strcat(string, "\r"); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 183 ".\\lexer.l"
{ strcat(string, "\e"); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 184 ".\\lexer.l"
{ strcat(string, " "); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 185 ".\\lexer.l"
{ strcat(string, "\\");}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 186 ".\\lexer.l"
{ strcat(string, "\""); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 187 ".\\lexer.l"
{ strcat(string, "#"); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 190 ".\\lexer.l"
{ strcat(string, "\\\""); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 191 ".\\lexer.l"
{ strcat(string, "'"); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 195 ".\\lexer.l"
{ 
                                sscanf(yytext + 1, "%o", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 202 ".\\lexer.l"
{ 
                                sscanf(yytext + 2, "%x", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 209 ".\\lexer.l"
{ 
                                printf("String literal: \"%s\" \n", string);
                                BEGIN(INITIAL);
                        }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 214 ".\\lexer.l"
{ 
                            printf("String literal: \"%s\" \n", string);
                            BEGIN(INITIAL);
                        }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 220 ".\\lexer.l"
{ printf("Found single-line comment: %s\n", yytext + 1); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 224 ".\\lexer.l"
{
    BEGIN(ML_COMMENT);
    printf("Found multiline comment:\n");
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 230 ".\\lexer.l"
{
    BEGIN(INITIAL);
    printf("%s", yytext);
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 237 ".\\lexer.l"
{ 
    
    char* cleanedText = removeUnderscores(yytext);
    int number = atoi(cleanedText);
    printf("Found integer: %d\n", number); 
    free(cleanedText); 
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 244 ".\\lexer.l"
{ 
    char* cleanedText = removeUnderscores(yytext);
    int number = strtol(cleanedText, NULL, 16);
    printf("Found hexadecimal integer: %d\n", number); 
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 250 ".\\lexer.l"
{
    char* cleanedText = removeUnderscores(yytext + 2);
    int number = strtol( cleanedText, NULL, 2);
    printf("Found binary integer: %d\n", yytext);
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 256 ".\\lexer.l"
{ 
    char* cleanedText = removeUnderscores(yytext);
    double number = atof(cleanedText);
    printf("Found floating-point number: %f\n", number); 
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 262 ".\\lexer.l"
{ 
    char* cleanedText = removeUnderscores(yytext);
    double number = atof(cleanedText);
    printf("Found floating-point number with exponent: %f\n", number); 
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 268 ".\\lexer.l"
{
    char* cleanedText = removeUnderscores(yytext);
    double number = atof(cleanedText);
    printf("Found number with exponent: %f\n", number); 
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 274 ".\\lexer.l"
{
    printf("Error: Underscore is repeated several times in a row: %s\n", yytext); 
}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 278 ".\\lexer.l"
{
    printf("Error: Underscore is repeated several times in a row: %s\n", yytext); 
}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 282 ".\\lexer.l"
{
    printf("Error: Underscore is repeated several times in a row: %s\n", yytext); 
}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 287 ".\\lexer.l"
{printf("Error: Dot at the start of a number: %s\n", yytext); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 289 ".\\lexer.l"
{printf("Error: Dot is repeated several times in a row: %s\n", yytext); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 292 ".\\lexer.l"
ECHO;
	YY_BREAK
#line 1700 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DOUBLE_QUOTE_STRING):
case YY_STATE_EOF(SINGLE_QUOTE_STRING):
case YY_STATE_EOF(ML_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 338 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 338 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 337);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 292 ".\\lexer.l"


int main(int argc, char** argv) {
    if (argc != 2) {
        printf("You need to specify file name");
        return 1;
    }

    const char *filename = argv[1];
    
    FILE *file = fopen(filename, "r");
    if (file == NULL) {
        printf("File opening error");
        return 1;
    }

    yyin = file;

    while (yylex() != 0);

    fclose(file);

    return 0;
}

 char* removeUnderscores(const char* input) {
    char* result = malloc(strlen(input) + 1);
    int resultIndex = 0;
    
    for (int i = 0; input[i]; i++) {
        if (input[i] != '_') {
            result[resultIndex++] = input[i];
        }
    }
    
    result[resultIndex] = '\0';
    return result;
}

